# UniPi Student Notes
# CI Template - you shouldn't have a reason to edit this

sudo: required
language: generic
services: docker

script:
  - docker run --mount src=$TRAVIS_BUILD_DIR,target=/usr/src/tex,type=bind dxjoke/tectonic-docker /bin/sh -c 'for i in *.tex; do tectonic $i; done'

after_success:
  - body="**Latest revision**\n";
    for i in *.pdf; do
            body+="[$i](https://github.com/$TRAVIS_REPO_SLUG/releases/download/continuous/main.pdf)\n";
    done;
    export UPLOADTOOL_BODY=$body
  - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
  - bash upload.sh *.pdf;

branches:
  except:
    - /^(?i:continuous)$/
